# Generated by Django 6.0.4 on 2026-04-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereaction',
            name='reaction',
            field=models.CharField(choices=[('heart', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😡'), ('like', '👍')], max_length=10),
        ),
    ]
