# Generated by Django 6.0.4 on 2026-05-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_messagereaction_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageread',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
